import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Menu } from "@components/Menu";
import Link from "next/link";
import { NavLoginButton } from "./components/Button/NavLoginButton";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ToastContainer
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="colored"
        />
        <nav className="navWrapper">
          <Link href={"/"}>
            <h1 className="mainTitle">Rental Assist</h1>
          </Link>
          <NavLoginButton />
        </nav>
        <div className="mainWrapper">
          <aside>
            <Menu />
          </aside>
          <div className="childrenWrapper">{children}</div>
        </div>
      </body>
    </html>
  );
}
